services:
  - type: web
    name: workbridge-frontend
    runtime: static
    region: singapore
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
